version: '3.8'

name: resource-service

services:
  postgres:
    image: postgres:11.19-alpine
    container_name: db_resource
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "${DB_POSTGRES_PORT:-5433}:5432"