server:
  port: ${SERVER_PORT:8181}

spring:
  application:
    name: ${RESOURCE_SERVICE_NAME:resource}
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5632}/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

client:
  metadata:
    name: ${SONG_METADATA_NAME}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true