server:
  port: ${SERVER_PORT:8187}

spring:
  application:
    name: ${PROCESSOR_SERVICE_NAME:processor}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true